### ISSUE TITLE
ChatSanitizer.lua:76: attempt to concatenate field '?' (a nil value)

### ISSUE THREAD

**Issue by sWxJaPkT** [Aviana/ChatSanitizer#7]
Interface\AddOns\ChatSanitizer\ChatSanitizer.lua:76: attempt to concatenate field '?' (a nil value)

I get this error after a few minutes of playing wow

Any help would be most appreciated

**Comment by Steffanization** [comment]
Got the exact same problem, have you figured out anything?

**Comment by Aviana** [comment]
fixed i guess

**Comment by Steffanization** [comment]
I have the same problem, and I had to remove it because everytime I just hovered I get the error, so I have no clue as to if normal whispers also get blocked.

**Comment by Aviana** [comment]
Download the new version?

**Comment by Steffanization** [comment]
I have tried that, but with no help to the error

**Comment by Steffanization** [comment]
and also removed WDB and such WTF and such
